apiVersion: v1 
kind: PersistentVolume
metadata:
  name: database
  labels:
    volumes: my-volume
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  nfs:
    path: "/exports"
    server: 192.168.0.1