apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: kuard-proxy
spec:
  virtualhost:
    fqdn: kuard.local
  routes:
  - conditions:
    - prefix: /
    services:
    - name: kuard-service
      port: 80